### ISSUE TITLE
Firefox runbox errors

### ISSUE THREAD

**Issue by tomByrer** [isomorphic-git/isomorphic-git.github.io#19]
At https://isomorphic-git.github.io/docs/browser.html

Running the **Now let's pick a directory to work in."* section I get the following error in Fx Quantum 61 Linux (the default browser for my distro), but works in Chrome Version 67.0.3396.87

`TypeError: e.attachShadow is not a function[Learn More] object-inspector.min.js:1:371 `

**Comment by wmhilton** [comment]
Yay! works for me now FF 61.0 64-bit on Windows (without the default settings, not with the `about:config` hack)
